WINDOW_WIDTH = 1020
WINDOW_HEIGHT = 900
FPS = 60
TILE_SIZE = (60, 60)
SNAKE_COLOUR = "blue"
APPLE_COLOUR = "red"
TEXT_COLOUR = "black"
FONT = "serif"
SNAKE_HEAD_COLOUR = "white"
SCORE_TEXT = "Score: "
COLOUR_1 = "dark green"
COLOUR_2 = "green"
HIGH_SCORE_TEXT = "High Score: "
PLAY_AGAIN_TEXT = "Enter ENTER to play again!"
HIGH_SCORE_FILE_NAME = "highscore.txt"